apiVersion: v1
kind: Service
metadata:
  name: xinrui-service
  labels:
    app: testxinrui
    label: quick
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
